apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpture-proxy
spec:
  selector:
    matchLabels:
      app: kpture-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: kpture-proxy
    spec:
      containers:
      - name: kpture-proxy
        image: gmtstephane/kptureproxy:0.0.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kpture-proxy-service
  labels:
    service: kpture-proxy-service
spec:
  type: NodePort
  selector:
    app: kpture-proxy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 
